[workspace]
resolver = "2"
members = ["app", "bootloader"]

[profile.release]
strip = true
codegen-units = 1
debug = false
lto = "fat"
opt-level = "z"
incremental = true

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true
